version: '3'
services:

  # Uses npm install + webpack to create a shared volume that nginx calls from. 
  memes:
    image: fishnet/memes
    container_name: memes-files
    volumes:
      - memes:/data

  webserver:
    image: nginx:alpine
    container_name: memes-nginx
    restart: unless-stopped
    ports: 
      - "80:80"
    volumes:
      - ./src:/var/www/src
      - memes:/var/www
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - memes

volumes:
  memes:
    driver: local
